### ISSUE TITLE
EF Core 3.1: New Overrides

### ISSUE THREAD

**Issue by JakenVeina** [romantitov/MockQueryable#25] opened 2020-01-12 04:58 UTC
Protip: When supporting EF Core 3.1, mocked `DbSet<>` objects need to additionally override the newly-added methods `.AsQueryable()` and `.AsAsyncEnumerable()` (which simply `return this;`) within `BuildMockDbSet()` calls.

Anyone who (like me) was using the `.AsQueryable()` extension method upon a `DbSet<>` in production code will, after upgrade to 3.1, be calling the methods upon `DbSet<>` instead. In my case, this meant that instead of getting a cast of the `DbSet<>` to `IQueryable<>` I was getting an auto-generated default implementation from Moq's `DefaultValueProvider`, which is basically `Array.Empty<T>.AsQueryable()`.

**Comment by romantitov** [comment] 2020-01-21 18:24
@JakenVeina  thank you for the feedback. 
Not sure that the issue is clear for me. 
I've tried to run tests in the solution with EF Core 3.1.1, and all tests is green.  Could you provide an example of failed test  to reproduce the issue?

**Comment by JakenVeina** [comment] 2020-01-23 03:37
Basically, I was doing
```cs
var query = _context.Set<MyEntity>()
    .AsQueryable();

if(...)
    query = query.Where(...);
```
in a method under test. The `.AsQueryable()` call was just my way of casting to `IQueryable<T>` so I can re-use the variable `query`.

The change is that in 3.0, `.AsQueryable()` resolves to the LINQ extension method, while in 3.1, it resolves to the new method that was added to `DbSet<>`. So, when I've configured the test to have `_context.Set<MyEntity>()` return a mocked `DbSet<>` the behavior suddenly changed. It took me a couple hours to figure out why the set was coming back empty, and it was that `Mock<DbSet<>>` specifically has logic to return something other than `null` for methods returning `IQueryable<T>` It just builds a queryable out of an empty array.

Easily worked around on my end, once I realized what the issue is, but this seems like a good candidate to be added to the `.Setup()` calls that `MockQueryable` does for you.

**Comment by romantitov** [comment] 2020-01-25 17:52
The issue fixed in release 3.1.1

**Closed by romantitov** 2020-01-25 17:52 UTC

**Comment by likemike91** [comment] 2020-03-19 08:56
Is that also fixed for NSubstitute?
Unfortunately I get the same error when using NSubstitute and I didn't see the fix in the code of the NSubstitute extension?

**Comment by romantitov** [comment] 2020-05-28 08:33
@likemike91 could you open a new issue if you still facing with the error

**Comment by krilllind** [comment] 2021-05-23 20:12
@likemike91 Created a new ticket and PR. Hopefully we can get this fixed 👍
